# Generated by Django 4.2.21 on 2025-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsFlash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "region",
                    models.CharField(
                        choices=[("国内", "国内"), ("国外", "国外")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("summary", models.CharField(max_length=60)),
                ("detail", models.TextField()),
                ("image_url", models.CharField(max_length=255)),
                ("source_url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "简讯",
                "verbose_name_plural": "简讯",
                "db_table": "news_flash",
            },
        ),
    ]
